name: Generate Snake

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare output folder
        run: mkdir -p dist

      - name: Generate Snake SVG (dark)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: alan-felipe-dev
          theme: dark
          output: dist/github-contribution-grid-snake-dark.svg

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
