name: Generate Snake Animation

on:
  schedule: # roda a cada 12 horas certinho
    - cron: "0 */12 * * *"
  workflow_dispatch: # permite rodar manualmente

jobs:
  build:
    name: Generate Snake
    runs-on: ubuntu-latest

    steps:
      # Gera a cobrinha
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: alan-felipe-dev
          outputs: dist/github-contribution-grid-snake.svg

      # Publica no branch output
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
